<div class="navbar">
	<div class="navbar-inner">    
		<a class="brand" href="<?php echo $this->url(array('controller' => 'products', 'action' => 'index')); ?>">Products</a>
		<a class="btn" id="products-create" href="<?php echo $this->url(array('controller' => 'products', 'action' => 'create')); ?>">Add a Product</a>
		<a class="btn" id="products-clear" href="<?php echo $this->url(array('controller' => 'products', 'action' => 'clear')); ?>">Clear The List</a>
	</div>
</div>
	
<div id="products-grid">
	<form class="form-inline">
		<div class="filters">
			<?php echo $this->form->category; ?>
		</div>
		
		<div class="content">
			<?php echo $this->render('products/index.ajax.phtml') ?>
		</div>
	</form>
</div>