<div class="btn-group">
	<a class="btn" href="<?php echo $this->url(array('controller' => 'products', 'action' => 'create')); ?>">Create a Product</a>
</div>

<?php /* echo $this->form; */ ?>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>

  	<?php foreach ($this->products as $product) { ?>
  	<tr>
      <td><?php echo $product->getId(); ?></td>
      <td><?php echo $product->getName(); ?></td>
      <td><?php echo $product->getCategory()->getName(); ?></td>
    </tr>
    <?php } ?>

  </tbody>
</table>		
