<!DOCTYPE html>
<html>
	<head>
    	<title>TDMS Pilot Task</title>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
    </head>
	<body>
    	    	
		<div class="container">
			<?php echo $this->layout()->content; ?>
		</div>
    	
    	<script src="/js/jquery.min.js"></script>
    	<script src="/js/bootstrap.min.js"></script>
    </body>
</html>